[0m[[0minfo[0m] [0mRunning MapReduce.MapReduceMaster [0m
[0m[[0minfo[0m] [0m[INFO] [05/31/2016 18:12:53.199] [main] [akka.remote.Remoting] Starting remoting[0m
[0m[[0minfo[0m] [0m[ERROR] [05/31/2016 18:12:53.536] [ClusterSystem-akka.remote.default-remote-dispatcher-13] [NettyTransport(akka://ClusterSystem)] failed to bind to /127.0.0.1:2551, shutting down Netty transport[0m
[0m[[31merror[0m] [0mException in thread "main" org.jboss.netty.channel.ChannelException: Failed to bind to: /127.0.0.1:2551[0m
[0m[[31merror[0m] [0m	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)[0m
[0m[[31merror[0m] [0m	at akka.remote.transport.netty.NettyTransport$$anonfun$listen$1.apply(NettyTransport.scala:415)[0m
[0m[[31merror[0m] [0m	at akka.remote.transport.netty.NettyTransport$$anonfun$listen$1.apply(NettyTransport.scala:411)[0m
[0m[[31merror[0m] [0m	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)[0m
[0m[[31merror[0m] [0m	at scala.util.Try$.apply(Try.scala:192)[0m
[0m[[31merror[0m] [0m	at scala.util.Success.map(Try.scala:237)[0m
[0m[[31merror[0m] [0m	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)[0m
[0m[[31merror[0m] [0m	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)[0m
[0m[[31merror[0m] [0m	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)[0m
[0m[[31merror[0m] [0m	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)[0m
[0m[[31merror[0m] [0m	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)[0m
[0m[[31merror[0m] [0m	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)[0m
[0m[[31merror[0m] [0m	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)[0m
[0m[[31merror[0m] [0m	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)[0m
[0m[[31merror[0m] [0m	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)[0m
[0m[[31merror[0m] [0m	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)[0m
[0m[[31merror[0m] [0m	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)[0m
[0m[[31merror[0m] [0m	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)[0m
[0m[[31merror[0m] [0m	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)[0m
[0m[[31merror[0m] [0m	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)[0m
[0m[[31merror[0m] [0m	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)[0m
[0m[[31merror[0m] [0mCaused by: java.net.BindException: Address already in use[0m
[0m[[31merror[0m] [0m	at sun.nio.ch.Net.bind0(Native Method)[0m
[0m[[31merror[0m] [0m	at sun.nio.ch.Net.bind(Net.java:436)[0m
[0m[[31merror[0m] [0m	at sun.nio.ch.Net.bind(Net.java:428)[0m
[0m[[31merror[0m] [0m	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)[0m
[0m[[31merror[0m] [0m	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)[0m
[0m[[31merror[0m] [0m	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)[0m
[0m[[31merror[0m] [0m	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)[0m
[0m[[31merror[0m] [0m	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)[0m
[0m[[31merror[0m] [0m	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)[0m
[0m[[31merror[0m] [0m	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)[0m
[0m[[31merror[0m] [0m	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)[0m
[0m[[31merror[0m] [0m	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[0m
[0m[[31merror[0m] [0m	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[0m
[0m[[31merror[0m] [0m	at java.lang.Thread.run(Thread.java:745)[0m
[0m[[0minfo[0m] [0m[INFO] [05/31/2016 18:12:53.597] [ClusterSystem-akka.remote.default-remote-dispatcher-5] [akka://ClusterSystem/system/remoting-terminator] Shutting down remote daemon.[0m
[0m[[0minfo[0m] [0m[INFO] [05/31/2016 18:12:53.602] [ClusterSystem-akka.remote.default-remote-dispatcher-5] [akka://ClusterSystem/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.[0m
[0m[[0minfo[0m] [0m[ERROR] [05/31/2016 18:12:53.609] [ClusterSystem-akka.remote.default-remote-dispatcher-13] [akka.remote.Remoting] Remoting system has been terminated abrubtly. Attempting to shut down transports[0m
[0m[[0minfo[0m] [0m[INFO] [05/31/2016 18:12:53.611] [ClusterSystem-akka.remote.default-remote-dispatcher-5] [akka://ClusterSystem/system/remoting-terminator] Remoting shut down.[0m
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1830)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1830)
	at scala.Option.foreach(Option.scala:236)
	at sbt.BuildCommon$class.toError(Defaults.scala:1830)
	at sbt.Defaults$.toError(Defaults.scala:35)
	at sbt.Defaults$$anonfun$runMainTask$1$$anonfun$apply$34$$anonfun$apply$35.apply(Defaults.scala:685)
	at sbt.Defaults$$anonfun$runMainTask$1$$anonfun$apply$34$$anonfun$apply$35.apply(Defaults.scala:683)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[0m[[31merror[0m] [0m(compile:[31mrunMain[0m) Nonzero exit code returned from runner: 1[0m
